-- =============================================================================
-- 毎朝 7:00 JST 日次ジョブ RPC
-- Crown awarding is defined in 030-crown-awards.sql / migrations/030_crown_awards.sql
-- Re-run that file after schema changes so run_daily_morning_job stays in sync.
-- =============================================================================

-- Prefer applying the full crown migration:
--   supabase/sql/030-crown-awards.sql
--
-- That file recreates run_daily_morning_job with:
--   1) pending → published
--   2) award_daily_crowns(yesterday JST)
--   3) retention pending count
--   4) daily_assignments + morning_digest notifications
